# Generated by Django 4.1.2 on 2022-11-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_type_booking_contact_booking_disque_booking_quantite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskJocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='file/images/diskjocker')),
                ('banniere_Img', models.ImageField(blank=True, null=True, upload_to='file/images/diskjocker')),
                ('banniere_Vid', models.FileField(blank=True, null=True, upload_to='file/videos/diskjocker')),
            ],
        ),
    ]
