# Generated by Django 4.1.3 on 2022-12-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_disque_artistes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disque',
            name='genre',
        ),
        migrations.AddField(
            model_name='disque',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genres', to='Store.genre'),
        ),
    ]
