# Generated by Django 4.1.3 on 2023-01-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_banniere'),
    ]

    operations = [
        migrations.AddField(
            model_name='disque',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
